language: shell
os:
  - linux
  - windows
  - osx
addons:
  apt:
    packages:
    - gcc-multilib # https://stackoverflow.com/questions/12591629/gcc-cannot-find-bits-predefs-h-on-i686
    - g++-multilib
script:
  - curl -fsS https://dlang.org/install.sh | bash -s dmd-2.076.0
  - source ~/dlang/dmd-2.076.0/activate
  - test/run-tests.sh
