install:
  - git submodule update --init --recursive
  - ps: Start-FileDownload 'http://downloads.dlang.org/releases/2.x/2.076.0/dmd.2.076.0.windows.zip' -FileName 'dmd2.7z'
  - 7z x dmd2.7z > nul
  - set PATH=%CD%\dmd2\windows\bin;%CD%\dmd2\windows\bin64;%PATH%
  - dmd.exe --version
build_script:
  - bash test/run-tests.sh
